//
// wgstore.go
// FreeTurn Admin — WireGuard keypair storage
//
// /config/wg.json holds the keypairs generated by the panel for
// WireGuard peers. The router keeps only the PUBLIC key; the
// PRIVATE key lives here (0600, atomic writes) so the panel can
// re-issue the client config ("WG.config").
//

package admin

import (
	"crypto/ecdh"
	"crypto/rand"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"net"
	"os"
	"path/filepath"
	"time"
)

// WGKeypair is one panel-managed client keypair bound to a
// router peer (matched by PublicKey).
type WGKeypair struct {
	ID          string `json:"id"`
	WGInterface string `json:"wg_interface"`
	PublicKey   string `json:"public_key"`
	PrivateKey  string `json:"private_key"`
	AllowedAddr string `json:"allowed_address"`
	ClientID    string `json:"client_id,omitempty"`
	Comment     string `json:"comment"`
	CreatedAt   int64  `json:"created_at"`
}

// WGStore is the on-disk keypair database.
type WGStore struct {
	Version  int         `json:"version"`
	Keypairs []WGKeypair `json:"keypairs"`
}

// WGFile — storage path (private keys! 0600).
var WGFile = filepath.Join(ConfigDir, "wg.json")

// LoadWGStore reads the keypair store; a missing file is an
// empty store.
func LoadWGStore() (*WGStore, error) {
	var s WGStore
	if err := readJSONFile(WGFile, &s); err != nil {
		if os.IsNotExist(err) {
			return &WGStore{Version: 1}, nil
		}
		return nil, err
	}
	if s.Version == 0 {
		s.Version = 1
	}
	return &s, nil
}

// Save persists the store atomically with 0600 permissions.
func (s *WGStore) Save() error {
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	if err := ensureDir(ConfigDir); err != nil {
		return err
	}
	return writeFileAtomic(WGFile, data, 0o600)
}

// FindByPublicKey returns the keypair matching a router peer's
// public key (the canonical join), or nil.
func (s *WGStore) FindByPublicKey(pub string) *WGKeypair {
	for i := range s.Keypairs {
		if s.Keypairs[i].PublicKey == pub {
			return &s.Keypairs[i]
		}
	}
	return nil
}

// FindByClient returns the keypair bound to a client id, or nil.
func (s *WGStore) FindByClient(clientID string) *WGKeypair {
	if clientID == "" {
		return nil
	}
	for i := range s.Keypairs {
		if s.Keypairs[i].ClientID == clientID {
			return &s.Keypairs[i]
		}
	}
	return nil
}

// Remove removes the keypair with the given public key.
func (s *WGStore) Remove(pub string) {
	out := s.Keypairs[:0]
	for _, kp := range s.Keypairs {
		if kp.PublicKey != pub {
			out = append(out, kp)
		}
	}
	s.Keypairs = out
}

// GenerateKeypair creates an X25519 keypair (crypto/ecdh, stdlib),
// appends it to the store and returns it. Save() is NOT called —
// the caller persists after the router side succeeds.
func (s *WGStore) GenerateKeypair(wgInterface, allowedAddr, comment, clientID string) (*WGKeypair, error) {
	priv, err := ecdh.X25519().GenerateKey(rand.Reader)
	if err != nil {
		return nil, err
	}
	id := make([]byte, 16)
	if _, err := rand.Read(id); err != nil {
		return nil, err
	}
	kp := &WGKeypair{
		ID:          base64.RawURLEncoding.EncodeToString(id),
		WGInterface: wgInterface,
		PublicKey:   base64.StdEncoding.EncodeToString(priv.PublicKey().Bytes()),
		PrivateKey:  base64.StdEncoding.EncodeToString(priv.Bytes()),
		AllowedAddr: allowedAddr,
		ClientID:    clientID,
		Comment:     comment,
		CreatedAt:   time.Now().Unix(),
	}
	s.Keypairs = append(s.Keypairs, *kp)
	return kp, nil
}

// ipOf strips the /prefix from an address string.
func ipOf(addr string) string {
	if i := indexByte(addr, '/'); i >= 0 {
		return addr[:i]
	}
	return addr
}

func indexByte(s string, b byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == b {
			return i
		}
	}
	return -1
}

// NextFreeAddress returns the first free host /32 inside the
// interface subnet (ifaceCIDR like "10.10.20.1/24"). Skips the
// network/broadcast addresses, the interface's own IP and every
// address in used (bare IPs or with /prefix). Returns "" when the
// pool is exhausted or the subnet is too small.
func NextFreeAddress(ifaceCIDR string, used map[string]bool) string {
	ip, ipnet, err := net.ParseCIDR(ifaceCIDR)
	if err != nil {
		return ""
	}
	ones, bits := ipnet.Mask.Size()
	if bits != 32 {
		return ""
	}
	hosts := uint64(1) << uint(32-ones)
	if hosts <= 2 {
		return "" // /31 or smaller — no host addresses
	}
	base := binary.BigEndian.Uint32(ip.Mask(ipnet.Mask).To4())
	for i := uint64(1); i < hosts-1; i++ {
		addr := make(net.IP, 4)
		binary.BigEndian.PutUint32(addr, base+uint32(i))
		if used[addr.String()] {
			continue
		}
		return addr.String() + "/32"
	}
	return ""
}

// addrInSubnet reports whether the given address (with /prefix)
// lies inside ifaceCIDR ("10.10.20.1/24").
func addrInSubnet(addr, ifaceCIDR string) bool {
	ip, _, err := net.ParseCIDR(addr)
	if err != nil {
		return false
	}
	_, ipnet, err := net.ParseCIDR(ifaceCIDR)
	if err != nil {
		return false
	}
	return ipnet.Contains(ip)
}

// buildClientConfig assembles the WireGuard client config in the
// same format the URI generator embeds (uriExportDataCollector).
func buildClientConfig(privateKey, address, serverPublicKey, endpoint, dns string) string {
	return "[Interface]\n" +
		"PrivateKey = " + privateKey + "\n" +
		"Address = " + address + "\n" +
		"DNS = " + dns + "\n" +
		"[Peer]\n" +
		"PublicKey = " + serverPublicKey + "\n" +
		"AllowedIPs = 0.0.0.0/0\n" +
		"Endpoint = " + endpoint + "\n" +
		"PersistentKeepalive = 25"
}
